baseURL = "https://viphouse.szczecin.pl/"
languageCode = "pl-PL"
title = "Viphouse"
theme = "osprey-delight"
canonifyURLS = true
tags = ["Impreza", "Szczecin", "Aparatament", "Wynajem", "Bankiet",
"Party", "Wesele", "Spotkania", "Deptak Bogusława", "Centrum"]
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true

[Params]
  description = "Apartament VipHouse"
  tagline = "Miejsce na twoją imprezę"
  logoBig = "/images/viphouse-logo.png"
  logoSmall = "/images/viphouse-small.png"
  background = "background.jpg"
  favicon = "favicon.png"
  enforceSinglePage = false
  copyright = true
  credit = true

[Params.Feat]
  useLazySizes = true 

[Params.Social]

[Params.Image.Gallery]
  resize = "1000x"

[[menu.main]]
  name = "Impreza"
  identifier = "party"
  url  = "/#party"
  weight = 1
[[menu.main]]
  name = "Galeria"
  identifier = "gallery"
  url  = "/#gallery"
  weight = 2
[[menu.main]]
  name = "Video"
  identifier = "clips"
  url  = "/#clips"
  weight = 3
[[menu.main]]
  name = "O lokalu"
  identifier = "about"
  url  = "/#about"
  weight = 4
