baseURL = "http://viphouse.szczecin.pl/"
languageCode = "pl-PL"
title = "Viphouse"
theme = "osprey-delight"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true

[Params]
  description = "Apartament VipHouse"
  tagline = "Miejsce na twoją imprezę"
  logoBig = "/images/viphouse-logo.png"
  logoSmall = "/images/viphouse-small.png"
  favicon = "favicon.png"
  enforceSinglePage = false
  copyright = true
  credit = true

[Params.Feat]
  lazyloading = true

[[menu.main]]
  name = "Impreza"
  url  = "/#party"
  weight = 1
[[menu.main]]
  name = "Galeria"
  url  = "/#gallery"
  weight = 2
[[menu.main]]
  name = "Video"
  url  = "/#clips"
  weight = 3
[[menu.main]]
  name = "O lokalu"
  url  = "/#about"
  weight = 4
