name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout sumbodules
        uses: textbook/git-checkout-submodule-action@2.1.1
      - name: Build Hugo
        uses: lowply/build-hugo@v0.82.1
      - name: S3 Deploy
        uses: raulanatol/aws-s3-docker-action@v1.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET_NAME: viphouse.szczecin.pl
          SOURCE: public
          WITH_DELETE: true
          
