name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Hugo
        uses: lowply/build-hugo@v0.82.1
      - name: Deploy
        run: echo "Hello World"
